### ISSUE TITLE
make golangci-lint fails

### ISSUE THREAD

**Issue by mythi** [containers/nri-plugins#24]
...with a bunch of linter errors (`golangci-lint has version v1.50.1`)

**Comment by fmuyassarov** [comment]
Perhaps it would be also good to add a github action to run golangci-lint as part of presubmit?

**Comment by klihub** [comment]
> Perhaps it would be also good to add a github action to run golangci-lint as part of presubmit?

Yes, once we have fixed this. It is a known issue and the reason why we haven't enabled running golangci-lint as part of our github actions yet.

**Comment by fmuyassarov** [comment]
I have submitted a fix for all the issues currently reported by the linter. Maybe we can enable it once https://github.com/containers/nri-plugins/pull/25 gets merged.

**Comment by klihub** [comment]
All known issues should be fixed in latest `main/HEAD` and in `v0.8.0`, golangci-lint enabled in CI.
