### ISSUE TITLE
Issues with balloons helm installation

### ISSUE THREAD

**Issue by askervin** [containers/nri-plugins#99]
Make sure that helm installation of the balloons policy works, applies proper CPU frequencies (use kHz instead of MHz in sample CPU frequencies), and implement a e2e test for it.

**Comment by changzhi1990** [comment]
Use this command to install the helm charts

```
helm install balloon .  --namespace kube-system
```

**Comment by changzhi1990** [comment]
I think we can add some documents to clarify this.

**Comment by askervin** [comment]
Closing as helm is used now as a default method for deploying policies in e2e tests and documentation has been updated. Feel free to reopen or file new issue if there are any problems with helm installation.
